import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { devices } from "../../lib/seed/catalog";

const pages: Record<string, { title: string; kicker: string; intro: string; sections: Array<[string, string]> }> = {
  methodology: { title: "Review methodology", kicker: "Repeatable by design", intro: "Circuit Media separates sourced facts, lab observations, analysis and opinion so readers can audit the path to every conclusion.", sections: [["Specification verification","Provider payloads are stored untouched, normalized into typed fields, checked for conflicts and linked to the source URL and verification date."],["Editorial testing","A production lab workflow covers design, display, sustained performance, cameras, software, battery, connectivity and value. Fixture pages never pretend that missing lab results exist."],["Scoring","Category scores are editorial. Affiliate relationships, popularity and AI summaries do not alter a score. We decline to name a comparison winner when evidence is insufficient."],["AI controls","AI receives verified database fields and source IDs, returns structured JSON, and is rejected when it introduces unsupported values."]] },
  "editorial-policy": { title: "Editorial policy", kicker: "Independent judgment", intro: "Commercial relationships do not decide what we cover, how we test, or what we conclude.", sections: [["Separation","Editorial staff control reviews and recommendations. Sponsored work is labelled and visually separated."],["Review units","We disclose whether a device was purchased, borrowed, or supplied. Long-term updates disclose any change in testing conditions."],["Corrections","Material errors are corrected transparently with a timestamp and short change note."],["Conflicts","Writers disclose relevant financial or personal relationships before assignment."]] },
  corrections: { title: "Request a correction", kicker: "Accuracy is a process", intro: "Found a questionable specification, source mismatch, or editorial error? Send the exact page, field and better primary source.", sections: [["What to include","Page URL, field or passage, your suggested correction, and an authoritative source URL."],["What happens next","The data desk checks the provider payload, current source, regional variant and edit history before changing the public record."],["Response target","High-impact factual issues are prioritized. A correction note is added when a published conclusion materially changes."],["Contact","Email corrections@circuit-media.com."]] },
  sources: { title: "Data sources", kicker: "Every fact has a trail", intro: "Circuit Media reads a live device catalog for brands, device lists, full specifications and photos. A local analysis cache speeds recommendations and offline fallback.", sections: [["Primary source","Browse, search and product pages fetch live from the connected device specification catalog. The brand directory covers every manufacturer listed there."],["Images","Product photos are loaded from the live catalog record. No AI-generated image is ever used as an exact product photo."],["Prices","Displayed prices are the live catalog-listed figures, not retail offers. Unknown regional prices display “Varies by region”."],["Local cache",`${devices.length} devices are kept in a local analysis cache for recommendations and offline fallback. Refresh with node scripts/seed.mjs.`]] },
  privacy: { title: "Privacy policy", kicker: "Plain-language privacy", intro: "Circuit Media is designed to work without selling personal data or requiring sign-in for public research.", sections: [["Data collected","Basic request logs, abuse-prevention signals and user-submitted review content. Production analytics should be privacy-preserving and documented here."],["Local preferences","Theme preference is saved only in the visitor’s browser."],["Retention","Operational logs and moderation records should use documented retention limits."],["Rights","Contact privacy@circuit-media.com to request access or deletion after production identity controls are configured."]] },
  terms: { title: "Terms & conditions", kicker: "Use the evidence wisely", intro: "Circuit Media provides research and commentary, not a guarantee that a product or retailer will meet every visitor’s needs.", sections: [["Accuracy","We work to verify information but manufacturers can change regional variants, availability and software behavior."],["User content","Submitted reviews must be truthful, relevant and free from abusive or unlawful material."],["Availability","Services may change while provider maintenance, corrections or security work is underway."],["Liability","Make purchasing, health and safety decisions using manufacturer documentation and professional advice where appropriate."]] },
  "affiliate-disclosure": { title: "Affiliate disclosure", kicker: "Revenue, disclosed", intro: "Some outbound retailer links may earn Circuit Media a commission. That must never change a score, ranking or recommendation.", sections: [["Current fixture","The demonstration uses manufacturer links and no live affiliate offers."],["Future offers","PricingProvider records identify retailer, timestamp, price, currency and affiliate URL separately."],["Editorial firewall","Commerce staff cannot alter lab results or editorial conclusions."],["Reader cost","Eligible affiliate commissions do not change the checkout price shown by a retailer."]] },
  "ai-disclosure": { title: "AI content disclosure", kicker: "Assisted, never disguised", intro: "AI-generated text is labelled, evidence-constrained and stored separately from professional and user reviews.", sections: [["Permitted uses","Normalization support, plain-language summaries, evidence-based pros and cons, translation and comparison explanations."],["Inputs","Only verified database fields and their source records are provided for factual summaries."],["Validation","Structured output is rejected when it cites unknown sources or introduces unsupported values."],["Approval","Low-confidence or conflicting output remains pending until a human approves it."]] },
};

export async function generateMetadata({ params }: { params: Promise<{ info: string }> }): Promise<Metadata> { const page = pages[(await params).info]; return page ? { title: page.title, description: page.intro } : { title: "Page not found" }; }
export default async function InfoPage({ params }: { params: Promise<{ info: string }> }) { const page = pages[(await params).info]; if (!page) notFound(); return <main><section className="policy-hero"><div className="shell"><span className="section-kicker lime">{page.kicker}</span><h1>{page.title}</h1><p>{page.intro}</p></div></section><article className="policy-content shell">{page.sections.map(([title, body], index) => <section key={title}><span>0{index + 1}</span><div><h2>{title}</h2><p>{body}</p></div></section>)}<div className="policy-cta"><strong>Still have a question?</strong><p>Contact the Circuit Media data desk or inspect the provider-ready API documentation.</p><Link className="lime-button" href="/admin">Open data desk ↗</Link></div></article></main>; }
